# Generated by Django 2.1.5 on 2020-05-18 10:47

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location=None), upload_to='menu_item_img'),
        ),
    ]
