# Generated by Django 2.1.5 on 2020-05-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200518_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('small_price', models.FloatField(blank=True, null=True)),
                ('large_price', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
