# Generated by Django 2.1.5 on 2020-05-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_addition'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_type',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
